### ISSUE TITLE
Declaration compatibility error

### ISSUE THREAD

**Issue by ogrosko** [romm/NotiZ#169]
I'm getting this error:
```
Fatal error: Declaration of CuyZ\Notiz\ViewHelpers\Slot\RenderViewHelper::compile($argumentsName, $closureName, &$initializationPhpCode, TYPO3\CMS\Fluid\Core\Parser\SyntaxTree\AbstractNode $node, TYPO3\CMS\Fluid\Core\Compiler\TemplateCompiler $compiler) must be compatible with TYPO3Fluid\Fluid\Core\ViewHelper\ViewHelperInterface::compile($argumentsName, $closureName, &$initializationPhpCode, TYPO3Fluid\Fluid\Core\Parser\SyntaxTree\ViewHelperNode $node, TYPO3Fluid\Fluid\Core\Compiler\TemplateCompiler $compiler) in /var/www/html/web/typo3conf/ext/notiz/Classes/ViewHelpers/Slot/RenderViewHelper.php on line 0
```

typo3: 8.7.19

**Comment by ogrosko** [comment]
When I changed classes to:
`TYPO3Fluid\Fluid\Core\Parser\SyntaxTree\ViewHelperNode` and
`\TYPO3Fluid\Fluid\Core\Compiler\TemplateCompiler`

all works fine

**Comment by romm** [comment]
Thank you for your report.

Did you have this error during runtime? TYPO3 normally creates an alias for this class, see:

https://github.com/TYPO3/TYPO3.CMS/blob/05185631e8b98a81340442ac1dd0b163c2c771cc/typo3/sysext/fluid/Migrations/Code/ClassAliasMap.php#L6

Are you on a Composer based project?

**Comment by ogrosko** [comment]
Hi, yes project is composer based 
I'm getting this error during event dispatching. First time it's called right, then this error occurs. Until I clear all caches, then again it's called right and runs only once and again error occurs.

I know typo3 class alias mapping and wondering why this happens 🤔

**Comment by romm** [comment]
I tested with same TYPO3 version on my platform, the issue didn't appear.

I also searched for where the alias-mapping is done, could you try some debug work inside the generated file `vendor/composer/autoload_alias_loader_real.php`; put this:

```php
var_dump($classAliasMap);
die('foo');
```

And see if `typo3\cms\fluid\core\parser\syntaxtree\abstractnode` maps to `TYPO3Fluid\Fluid\Core\Parser\SyntaxTree\ViewHelperNode`.

**Comment by ogrosko** [comment]
Using other server it works fine.

**Comment by romm** [comment]
Ok, hope this won't bother you again.

Thanks for the report anyway. 😉
