### ISSUE TITLE
ObjectManager is injected though the used trait re-retrieves it from the service locator

### ISSUE THREAD

**Issue by cedricziel** [romm/NotiZ#21]
https://github.com/CuyZ/NotiZ/blob/e6ac779c665c6d142f129ca3cc032ab66bf2ae2c/Classes/Service/Container.php#L37

**Comment by cedricziel** [comment]
Now I see what you did there. - Just a question: Why are you making the dependency injection static instead of injecting services where they are used?

**Comment by romm** [comment]
Hi Cedric, thanks for the feedback. :)

Actually, there are several reasons why this container class exists :

- It's a sort of shortcut for some places where dependency injection can just not be used (for instance when some class is instantiated via `GeneralUtility::makeInstance()`). This allows us not to be forced to manually instantiate Extbase's `ObjectManager`, then get the wanted object instance, just call a static method instead. For instance:
  https://github.com/CuyZ/NotiZ/blob/e6ac779c665c6d142f129ca3cc032ab66bf2ae2c/Classes/Service/Scheduler/Scheduler.php#L73-L78
- There are some places where DI can't be used at all, for instance:
  https://github.com/CuyZ/NotiZ/blob/e6ac779c665c6d142f129ca3cc032ab66bf2ae2c/Classes/Definition/Tree/EventGroup/Event/Connection/Signal.php#L57-L64
  This `Signal` object is serialized and put in cache, so the dependencies can't be serialized as well, meaning the service needs to be retrieved when it needs to be used.
