### ISSUE TITLE
Editor access not possible

### ISSUE THREAD

**Issue by ogrosko** [romm/NotiZ#222]
Hello @romm,

When access for Manager module is granted to Editors after createning notification this error pop ups (see screen below). Since all notifications are created with pid=0, it's not possible to grant access to editors with DB Mounts defined.

![image](https://user-images.githubusercontent.com/2938503/88299957-3c63f080-cd03-11ea-903d-e9d789490832.png)

**Comment by romm** [comment]
Hi @ogrosko, thanks for the report.

Could you try out #223 and confirm it fixes your issue?

**Comment by ogrosko** [comment]
Hi @romm 
Looks good 👍 
Thank you
