### ISSUE TITLE
Notifications in scheduler tasks not send

### ISSUE THREAD

**Issue by hirnschmalz** [romm/NotiZ#234]
I created a custom event in a Symfony Console Command. If the command is executed via the scheduler in the backend everything works as expected. If the relevant scheduler task is executed via CLI/Cronjob no notification is sent.

The problem seems to be a missing Signal/Slot configuration which is automatically generated under "normal" circumstances. In `\TYPO3\CMS\Extbase\SignalSlot\Dispatcher::dispatch()` no slot is found in line `131`.

Test in TYPO3 9 LTS with EXT:notiz 2.1.1

**Comment by romm** [comment]
Hello @hirnschmalz,

Can you try to update to the latest release and confirm if the issue you described has been solved?

**Comment by ogrosko** [comment]
I had a same issue with version `2.1.2`, after updating to `2.1.3` all good
