### ISSUE TITLE
Is this extension alive

### ISSUE THREAD

**Issue by hirnschmalz** [romm/NotiZ#239]
@romm I just wanted to know if there are any plans for further development of this extension. No code update since 3 years and no compatibility for TYPO3 CMS v10 or higher.

If this extension is no longer maintained a short note in the README would be nice.

**Comment by romm** [comment]
Hi @hirnschmalz sorry I did not do it sooner. I've updated the README with a note about it.

If you ever wanted to maintain the project, please tell me and we'll find a way to make you the new maintainer.

Have a good day.

**Comment by hirnschmalz** [comment]
Hi @romm thanks for clarification. I'll discuss this with my team and let you know if we are able to take care of the extension.
